# Generated by Django 5.0 on 2023-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Aircraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AircraftTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('passenger_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Aircraft_Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('baggage_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_in_kilogram', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Baggage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_mileage', models.IntegerField(blank=True, null=True)),
                ('current_mileage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Engines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Event_Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.TextField(blank=True, null=True, unique=True)),
                ('flight_delay_in_hours', models.IntegerField(blank=True, null=True)),
                ('time_of_arrival', models.TextField(blank=True, null=True)),
                ('time_of_departure', models.TextField(blank=True, null=True)),
                ('distance_traveled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.BooleanField(blank=True, null=True)),
                ('technical', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Flight_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Job_Title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_maintenance', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('odometer_id', models.AutoField(primary_key=True, serialize=False)),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('reading_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Odometer_Reading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Passengers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('start_of_work', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilots',
            fields=[
                ('pilot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_pilot', models.TextField(blank=True, null=True)),
                ('start_of_working', models.DateField(blank=True, null=True)),
                ('hours_passed', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pilots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('place_class', models.TextField(blank=True, null=True)),
                ('place_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tickets',
                'managed': False,
            },
        ),
    ]
